sudo: required
dist: trusty
language: cpp
      
os:
  - windows
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8
      
before_install:
        before_install:
#        - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then           ; fi
#        - if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then ; fi
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi

install:
        if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
                - sudo apt-get install qtbase5-dev g++-8
                - sudo apt-get install qt5-default qttools5-dev-tools
                - sudo apt-get install cmake cppcheck
        fi

script:
        - export CC=gcc-8
        - export CXX=g++-8
        - g++ -v
        - mkdir build
        - cd build 
        - cmake -DCMAKE_CXX_FLAGS="-std=c++14" -DCMAKE_PREFIX_PATH="/opt/qt59/" ..
        - make
        #- gprof ./QtDice  > gprof.log
        #- head gprof.log -n 100
        - cd ../src/ && cppcheck --quiet --force --error-exitcode=1 . 

notifications:
    email:
        - petross404@gmail.com
