language: cpp 
sudo: required

matrix:
    include:
    - compiler: gcc
        addons:
        apt:
            packages:
            - g++-5
    env: COMPILER=g++-5

    - compiler: gcc
        addons:
        apt:
            packages:
            - g++-6
    env: COMPILER=g++-6

    - compiler: clang
        addons:
        apt:
            packages:
            - clang-4
    env: COMPILER=clang++-4
    
    - compiler: clang
        addons:
        apt:
            packages:
            - clang-5
    env: COMPILER=clang++-5

os: 
    - linux

script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
    
notifications:
    email:
        - petross404@gmail.com
    
