language: cpp 
sudo: required
before_install:
        - sudo apt-get update -qq
        - sudo apt-get install qtbase5-dev
        - sudo apt-get install qt5-default qttools5-dev-tools
        - sudo apt-get install cmake

compiler:
        - clang
        - gcc
  
script:
        - mkdir build
        - cd build 
        - cmake ..
        - make

notifications:
    email:
        - petross404@gmail.com
    
