language: cpp 

compiler:
- clang
- gcc
    
os: linux

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make && make test
    
notifications:
    email:
        - petross404@gmail.com
    
