language: cpp 
sudo: required
before_install:
        - sudo apt-get install cmake qt5-dev

compiler:
        - clang
        - gcc
  
script:
        - mkdir build
        - cd build 
        - cmake ..
        - make

notifications:
    email:
        - petross404@gmail.com
    
